title: Carlos A. Planchón
author:
  name: Carlos A. Planchón
  email: carlosplanchon@cognitialabs.com
description: Any sufficiently advanced technology is indistinguishable from biology.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot
header_pages:
  - about.md
  - about-es.md
minima:
  skin: classic

# Polyglot configuration
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "media"]
parallel_localization: true
