# Site identity
title: Carlos A. Planchón
description: Any sufficiently advanced technology is indistinguishable from biology.

author:
  name: Carlos A. Planchón
  email: carlosplanchon@cognitialabs.com

url: "https://carlosplanchon.com"
baseurl: ""

# Theme
theme: minima
minima:
  skin: auto

# Analytics
google_analytics: G-JEL63P0Y9F

# Permalinks:
permalink: "/:categories/:year/:month/:day/:title:output_ext"

# Plugins
plugins:
  - jekyll-feed

# Header nav (Minima)
header_pages:
  - about.md
