title: Carlos A. Planch√≥n
author:
  name: carlosplanchon
  email: carlosandresplanchonprestes@gmail.com
description: Any sufficiently advanced technology is indistinguishable from biology.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
